[project]
name = "gitlab-deployment-changelog"
version = "0.0.3"
description = """Gitlab Deployment Changelog Creator - Get's the last
deployments for a specific environment and creates a changelog from the merge
requests and issues"""

authors = [
    {name = "Christoph Becker", email = "christoph.becker@exb.de"},
    {name = "Lukas Jesche", email = "lukas.jesche@exb.de"},
    {name = "Riccardo Padoan", email = "riccardo.padoan@exb.de"},
]
dependencies = [
    "flake8>=6.1.0",
    "pytest>=7.4.3",
    "pytest-cov>=4.1.0",
    "python-gitlab>=4.2.0",
    "python-decouple>=3.8",
    "pyyaml>=6.0.1",
    "loguru>=0.7.2",
    "requests>=2.31.0",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}


[tool]
[tool.pdm]
[tool.pdm.build]
includes = [
    "src/",
]

[tool.pdm.scripts]
changelog = "src/main.py"