name: Test & Release

on:
  push:
    branches:
      - packaging_semantic
      - main

jobs:
  test:
    name: Python ${{ matrix.python-version }} tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
#        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v3
        with:
          path: ~/.venv
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          pip install --user pdm
          pdm install -G :all
      - name: pytest
        run: pdm run pytest


  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    concurrency: push
    needs: [test]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install, Version and Upload
      run: |
        pip install --user pdm
        pdm install -G :all --dev --no-lock --no-editable
        pdm run semantic-release version
        pdm run twine upload dist/*
        pdm run semantic-release publish
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPOSITORY_USERNAME: __token__
        REPOSITORY_PASSWORD: ${{ secrets.REPOSITORY_PASSWORD }}
